#!/usr/bin/env python3
"""Representative marketplace few-shot compression regeneration demo.

This demo intentionally drives the normal ``pdd generate`` command boundary
while replacing the network call with a representative PDD Cloud marketplace
response. That keeps the touch point reproducible in CI while proving the same
client-side path used by live marketplace grounding:

- uncompressed and compressed generate invocations
- cloud ``examplesUsed`` grounding metadata
- prompt/evidence size reporting
- executable behavior checks on the regenerated output
"""

from __future__ import annotations

import importlib.util
import json
import os
import sys
from contextlib import contextmanager
from pathlib import Path
from typing import Any
from unittest.mock import patch

from click.testing import CliRunner

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from pdd.commands.generate import generate  # noqa: E402
from pdd.preprocess import preprocess  # noqa: E402

DEMO_DIR = Path(__file__).resolve().parent
PROMPT = DEMO_DIR / "prompts" / "ticket_classifier_python.prompt"
MARKETPLACE_EXAMPLES = DEMO_DIR / "fixtures" / "marketplace_examples.json"
GENERATED_DIR = DEMO_DIR / "generated"
REPORT_PATH = GENERATED_DIR / "marketplace_compression_report.json"

MARKETPLACE_FEW_SHOT_RAW = """
Marketplace few-shot pattern: preserve compact JSON and exact labels.

Input: "The app crashes when I click Save."
Output: {"category": "bug", "severity": "high"}

Input: "Please add dark mode to the dashboard."
Output: {"category": "feature_request", "severity": "medium"}

Input: "The README is missing install steps."
Output: {"category": "documentation", "severity": "low"}

Input: "Dashboard feels slow on mobile."
Output: {"category": "usability", "severity": "medium"}

Extended creator notes: this marketplace pattern was submitted from a verified
fix loop and contains extra narrative about support queues, routing policies,
dashboards, and escalation handling. Those notes are useful provenance but are
not part of the behavioral contract needed for regeneration.
"""

MARKETPLACE_FEW_SHOT_COMPRESSED = """
Marketplace few-shot pattern: preserve compact JSON and exact labels.
Input: "The app crashes when I click Save."
Output: {"category": "bug", "severity": "high"}
Input: "Please add dark mode to the dashboard."
Output: {"category": "feature_request", "severity": "medium"}
Input: "The README is missing install steps."
Output: {"category": "documentation", "severity": "low"}
Input: "Dashboard feels slow on mobile."
Output: {"category": "usability", "severity": "medium"}
"""

GENERATED_CODE = '''"""Generated by representative marketplace grounding demo."""

import json


def classify_ticket(text: str) -> dict[str, str]:
    lowered = text.lower()
    if "crash" in lowered or "error" in lowered or "fails" in lowered:
        return {"category": "bug", "severity": "high"}
    if "add" in lowered or "feature" in lowered or "please" in lowered:
        return {"category": "feature_request", "severity": "medium"}
    if "readme" in lowered or "docs" in lowered or "documentation" in lowered:
        return {"category": "documentation", "severity": "low"}
    if "slow" in lowered or "mobile" in lowered or "usability" in lowered:
        return {"category": "usability", "severity": "medium"}
    return {"category": "other", "severity": "low"}


def format_ticket_json(text: str) -> str:
    return json.dumps(classify_ticket(text), sort_keys=True)
'''


def _estimated_tokens(text: str) -> int:
    return -(-len(text) // 4)


@contextmanager
def _compression_env(enabled: bool):
    previous_mode = os.environ.get("PDD_CONTEXT_COMPRESSION")
    previous_examples = os.environ.get("PDD_COMPRESS_EXAMPLES")
    try:
        if enabled:
            os.environ["PDD_CONTEXT_COMPRESSION"] = "examples,contracts"
            os.environ["PDD_COMPRESS_EXAMPLES"] = "1"
        else:
            os.environ.pop("PDD_CONTEXT_COMPRESSION", None)
            os.environ.pop("PDD_COMPRESS_EXAMPLES", None)
        yield
    finally:
        if previous_mode is None:
            os.environ.pop("PDD_CONTEXT_COMPRESSION", None)
        else:
            os.environ["PDD_CONTEXT_COMPRESSION"] = previous_mode
        if previous_examples is None:
            os.environ.pop("PDD_COMPRESS_EXAMPLES", None)
        else:
            os.environ["PDD_COMPRESS_EXAMPLES"] = previous_examples


def _expanded_prompt_size(*, compress: bool) -> dict[str, int]:
    raw = PROMPT.read_text(encoding="utf-8")
    with _compression_env(compress):
        expanded = preprocess(
            raw,
            recursive=True,
            double_curly_brackets=False,
            compress=compress,
        )
        expanded = preprocess(
            expanded,
            recursive=False,
            double_curly_brackets=True,
            compress=compress,
        )
    return {
        "chars": len(expanded),
        "estimated_tokens": _estimated_tokens(expanded),
    }


class _FakeCloudResponse:
    def __init__(self, payload: dict[str, Any], examples_used: list[dict[str, Any]]) -> None:
        self.status_code = 200
        self._payload = payload
        self._examples_used = examples_used
        self.text = "{}"

    def raise_for_status(self) -> None:
        return None

    def json(self) -> dict[str, Any]:
        compressed = bool(self._payload.get("compress"))
        marketplace_context = (
            MARKETPLACE_FEW_SHOT_COMPRESSED
            if compressed
            else MARKETPLACE_FEW_SHOT_RAW
        )
        final_prompt_chars = len(self._payload["promptContent"]) + len(marketplace_context)
        return {
            "generatedCode": GENERATED_CODE,
            "totalCost": 0.01 if compressed else 0.02,
            "modelName": "representative-cloud-model",
            "examplesUsed": self._examples_used,
            "promptStats": {
                "clientPromptChars": len(self._payload["promptContent"]),
                "marketplaceFewShotChars": len(marketplace_context),
                "finalPromptChars": final_prompt_chars,
                "finalEstimatedTokens": _estimated_tokens(
                    self._payload["promptContent"] + marketplace_context
                ),
            },
        }


def _load_generated_module(path: Path):
    spec = importlib.util.spec_from_file_location(path.stem, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Could not import generated module at {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _assert_behavior(path: Path) -> None:
    module = _load_generated_module(path)
    assert module.classify_ticket("The app crashes when I click Save.") == {
        "category": "bug",
        "severity": "high",
    }
    assert module.classify_ticket("Please add dark mode to the dashboard.") == {
        "category": "feature_request",
        "severity": "medium",
    }
    assert module.classify_ticket("The README is missing install steps.") == {
        "category": "documentation",
        "severity": "low",
    }
    assert module.format_ticket_json("Dashboard feels slow on mobile.") == (
        '{"category": "usability", "severity": "medium"}'
    )


def _latest_evidence() -> dict[str, Any]:
    evidence_files = sorted((DEMO_DIR / ".pdd" / "evidence" / "devunits").glob("*.latest.json"))
    if not evidence_files:
        raise RuntimeError("pdd generate did not write an evidence manifest")
    return json.loads(evidence_files[-1].read_text(encoding="utf-8"))


def _run_generate(*, compress: bool, examples_used: list[dict[str, Any]]) -> dict[str, Any]:
    output_path = GENERATED_DIR / (
        "ticket_classifier_compressed.py" if compress else "ticket_classifier_uncompressed.py"
    )
    payloads: list[dict[str, Any]] = []
    responses: list[dict[str, Any]] = []

    def fake_post(_url: str, json: dict[str, Any], **_kwargs: Any) -> _FakeCloudResponse:
        payloads.append(dict(json))
        response = _FakeCloudResponse(json, examples_used)
        responses.append(response.json())
        return response

    args = [str(PROMPT), "--output", str(output_path), "--evidence"]
    if compress:
        args.append("--compress")

    with _compression_env(compress), patch(
        "pdd.code_generator_main.CloudConfig.get_jwt_token",
        return_value="representative-token",
    ), patch(
        "pdd.code_generator_main.CloudConfig.is_running_in_cloud",
        return_value=False,
    ), patch(
        "pdd.code_generator_main.CloudConfig.get_endpoint_url",
        return_value="https://promptdriven.ai/api/generateCode",
    ), patch(
        "pdd.code_generator_main.requests.post",
        side_effect=fake_post,
    ):
        result = CliRunner().invoke(
            generate,
            args,
            obj={
                "force": True,
                "quiet": True,
                "local": False,
                "temperature": 0.0,
                "strength": 0.5,
                "time": 0.25,
                "context": None,
            },
        )

    if result.exit_code != 0:
        raise RuntimeError(result.output or str(result.exception))
    if not payloads or not responses:
        raise RuntimeError("representative cloud generate path was not invoked")

    _assert_behavior(output_path)
    evidence = _latest_evidence()
    selected = evidence["generation"]["grounding"]["selected_examples"]
    if not selected or selected[0].get("source") != "marketplace":
        raise RuntimeError("evidence did not record marketplace grounding examples")

    return {
        "mode": "compressed" if compress else "uncompressed",
        "output": str(output_path.relative_to(DEMO_DIR)),
        "client_payload": {
            "chars": len(payloads[0]["promptContent"]),
            "estimated_tokens": _estimated_tokens(payloads[0]["promptContent"]),
        },
        "expanded_prompt": _expanded_prompt_size(compress=compress),
        "cloud_prompt_stats": responses[0]["promptStats"],
        "examples_used": selected,
        "behavior_passed": True,
    }


def run_demo() -> dict[str, Any]:
    os.chdir(DEMO_DIR)
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    examples_used = json.loads(MARKETPLACE_EXAMPLES.read_text(encoding="utf-8"))

    uncompressed = _run_generate(compress=False, examples_used=examples_used)
    compressed = _run_generate(compress=True, examples_used=examples_used)

    report = {
        "prompt": str(PROMPT.relative_to(DEMO_DIR)),
        "marketplace_fixture": str(MARKETPLACE_EXAMPLES.relative_to(DEMO_DIR)),
        "runs": [uncompressed, compressed],
        "reduction": {
            "client_prompt_chars": (
                uncompressed["client_payload"]["chars"]
                - compressed["client_payload"]["chars"]
            ),
            "final_prompt_chars": (
                uncompressed["cloud_prompt_stats"]["finalPromptChars"]
                - compressed["cloud_prompt_stats"]["finalPromptChars"]
            ),
            "final_estimated_tokens": (
                uncompressed["cloud_prompt_stats"]["finalEstimatedTokens"]
                - compressed["cloud_prompt_stats"]["finalEstimatedTokens"]
            ),
        },
    }
    REPORT_PATH.write_text(json.dumps(report, indent=2, sort_keys=True), encoding="utf-8")
    return report


def main() -> int:
    report = run_demo()
    before, after = report["runs"]
    print("=== Marketplace compression regeneration demo ===")
    print(f"Prompt: {report['prompt']}")
    print(f"Marketplace fixture: {report['marketplace_fixture']}")
    print(
        "Uncompressed final prompt: "
        f"{before['cloud_prompt_stats']['finalPromptChars']} chars / "
        f"{before['cloud_prompt_stats']['finalEstimatedTokens']} est. tokens"
    )
    print(
        "Compressed final prompt: "
        f"{after['cloud_prompt_stats']['finalPromptChars']} chars / "
        f"{after['cloud_prompt_stats']['finalEstimatedTokens']} est. tokens"
    )
    print(
        "Reduction: "
        f"{report['reduction']['final_prompt_chars']} chars / "
        f"{report['reduction']['final_estimated_tokens']} est. tokens"
    )
    print("Marketplace examples used:")
    for example in after["examples_used"]:
        print(f"  - {example['module']} ({example.get('title', 'untitled')})")
    print("Behavior checks: PASS")
    print(f"Report: {REPORT_PATH.relative_to(DEMO_DIR)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
